# Generated by Django 2.2.28 on 2026-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_images',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
