# Generated by Django 2.2.28 on 2026-03-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_project_cover_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cover_images',
            new_name='cover_image',
        ),
    ]
